GET http://localhost:3000/posts

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.ewogIF9pZDogbmV3IE9iamVjdElkKCI2MjE4YzI4OWJhYmM0NGY1NDZjNDc2ZDAiKSwKICBuYW1lOiAnTWFnZWR3d2F3MicsCiAgZW1haWw6ICdtYWdlZDF3MjNAMm1hZ2VkMi5jb20nLAogIHBhc3N3b3JkOiAnJDJiJDEwJDJ3cXZubE1IcHl4aktLQUpseC5JeHV1dTlsd2ZMU0t2YzNpLzMySmVZSnpSaGlLYndFTHEyJywKICBjcmVhdGVkQXQ6IDIwMjItMDItMjVUMTE6NTA6MzQuMDA4WiwKICB1cGRhdGVkQXQ6IDIwMjItMDItMjVUMTE6NTA6MzQuMDA4WiwKICBfX3Y6IDAKfQ.KGCn0U35VE7R1jO14s9-rPEkveYjXjbEXo5KsFvBCw0

###
GET http://localhost:3000/users?page=1&limit=2
###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title":"newwwst3",
    "body":"a long ww h333 to type out"
}
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Magedwwaw2",
    "email":"maged1w23@2maged2.com",
    "password":"12w3456"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"maged1w23@2maged2.com",
    "password":"12w3456"
}
###
GET http://localhost:3000/posts/62178aa0ad5061ad1e7e3061

###

GET http://localhost:3000/users/6217d83398c75f25ef908664

###
DELETE http://localhost:3000/posts/62178aa0ad5061ad1e7e3061
###
DELETE http://localhost:3000/users/6217d84398c75f25ef908666
###
PATCH http://localhost:3000/posts/62178aa0ad5061ad1e7e3061
Content-Type: application/json

{
    "title":"new title"
}
###
PATCH http://localhost:3000/users/6217d83398c75f25ef908664
Content-Type: application/json

{
    "name":"new user name"
}